#!/usr/bin/env python
# -*-coding:utf-8-*-

"""
每天十点
投资充值数据
"""

from openpyxl import load_workbook
import utils.public_conn_mysql as public_conn_mysql
import os
import smtplib
from email.mime.text import MIMEText
from email.header import Header
from email.mime.multipart import MIMEMultipart
from email.mime.application import MIMEApplication
import shutil
from openpyxl.utils import get_column_letter


def write_xlsx(data_list,filename):

	if os.path.exists(res_file):
		os.remove(res_file)
	shutil.copy(src_file,filename)
	wb = load_workbook(filename)  # 加载excel
	ws = wb.active

	#写入excel文件
	for line in range(len(data_list)):  # 遍历sql结果
		res = str(data_list[line]).split("\t")
		for col in range(len(res)):     #遍历每行分割结果
			ws.cell(row=line + 3, column=col + 1).value = res[col] #每个单元格写入相应的值
			#wb.save(res_file)

	#设置列宽
	for high in range(1,12):
		ws.column_dimensions[get_column_letter(high)].width = 15
	wb.save(res_file)
	print ("文件生成成功！")

def send_mail(filename,mailfile):
	#to_list = ["liaojinbo@xiaoniu66.com"]
	to_list = ["dengfeifei@xiaoniu66.com","xh.chen@xiaoniu66.com","linjun@xiaoniu66.com","linguorong@xiaoniu66.com","zhouhao13@xiaoniu66.com","donglinyong@xiaoniu66.com","liaojinbo@xiaoniu66.com"]
	config = {
		"from": "ndf.data_government@xiaoniu66.com",
		#"to": "liaojinbo@xiaoniu66.com",
		"serverip": "mail.xiaoniu66.com",
		"username": "ndf.data_government@xiaoniu66.com",
		"pwd": "data_dqc"
	}
	title = "小牛在线数据"

	msg = MIMEMultipart('related')

	content = u"Hi all:\n\n    请查收小牛在线投资充值提现数据，谢谢！"
	atttext = MIMEText(content, _subtype='plain', _charset='utf-8')
	msg.attach(atttext)

	att = MIMEApplication(open(filename,'rb').read())
	att.add_header('Content-Disposition','attachment',filename = mailfile)
	msg.attach(att)


	msg['Subject'] = Header(title, "utf-8")
	msg['From'] = config['from']
	msg['To'] = ",".join(to_list)

	s = smtplib.SMTP(config['serverip'])
	s.login(config['username'], config['pwd'])
	try:
		s.sendmail(config['from'], to_list, msg.as_string())
		print ("邮件发送成功！！")
	except:
		print ("发送失败")
		exit(1)


if __name__ == "__main__":
	v_sql = """
sql
"""
	print (v_sql)
	#conn = public_conn_mysql.ConnMysql("10.8.34.67","zxbi_rw","y-1stpp6RkpY","utf8")
	conn = public_conn_mysql.ConnMysql("172.22.22.122","bigdata","u2mgsuaVz74j5#xj1yCl","utf8")
	res = conn.select(v_sql)
	res_list = []

	for x in res:
		res_list.append(str(x[0])) # 生成查询结果数据集
	conn.close()
	for m in res_list:
		print (m,type(m))
	src_file = "/home/liaojinbo/zx_mail/moban_zxdata.xlsx"
	res_file = "/home/liaojinbo/zx_mail/投资充值提现.xlsx"
	#src_file = os.getcwd() + os.sep + "moban_inv.xlsx"
	#res_file = os.getcwd() + os.sep + "投资充值提现.xlsx"
	file_mail = "投资充值提现.xlsx"
	write_xlsx(res_list,res_file) # 将数据写入excel
	send_mail(res_file,file_mail)
